server:
  port: 8080
  servlet:
    context-path: /ai
spring:
  application:
    name: spring-ai
    version: 1.0.0
  # ai 配置相关
  ai:
    deepseek:
      api-key: sk-dbc8ed51cec741d388e0ca023d33b551
      base-url: http://192.168.2.54:9015
      chat:
        completions-path: /v1/chat/completions
    model:
      embedding:
    openai:
      api-key: sk-dbc8ed51cec741d388e0ca023d33b551
      custom:
        models:
          - baseUrl: https://dashscope.aliyuncs.com/api
            name: multimodalEmbeddingV1
            model-type: embedding
            app-key: sk-dbc8ed51cec741d388e0ca023d33b551
            options:
              model: multimodal-embedding-v1
              http-headers:
                Connection: keep-alive
                Upgrade: null
            embeddings-path: /v1/services/embeddings/multimodal-embedding/multimodal-embedding
          - baseUrl: http://192.168.2.54:9015
            name: multimodalEmbedding
            model-type: embedding
            app-key: sk-dbc8ed51cec741d388e0ca023d33b551
            options:
              model: multimodal-embedding-v1
#              http-headers:
#                Connection: keep-alive
#                Upgrade: null
            embeddings-path: /v1/embeddings
          - baseUrl: https://dashscope.aliyuncs.com/compatible-mode
            name: qwenPlus
            model-type: chat
            app-key: sk-dbc8ed51cec741d388e0ca023d33b551
            options:
              model: qwen-plus-2025-04-28
              http-headers:
                Connection: keep-alive
                Upgrade: null
            completionsPath: /v1/chat/completions
          - baseUrl: https://dashscope.aliyuncs.com/compatible-mode
            name: qwenMax
            model-type: chat
            app-key: sk-dbc8ed51cec741d388e0ca023d33b551
            options:
              model: qwen-max
              http-headers:
                Connection: keep-alive
                Upgrade: null
            completionsPath: /v1/chat/completions
          - baseUrl: https://dashscope.aliyuncs.com/api
            name: waxTurBo
            model-type: image_generation
            app-key: sk-dbc8ed51cec741d388e0ca023d33b551
            options:
              model: wanx2.1-t2i-turbo
              http-headers:
                Connection: keep-alive
                Upgrade: null
            completionsPath: /v1/services/aigc/text2image/image-synthesis
      chat:
        base-url: http://192.168.2.54:9015
#        options:
#          http-headers:
#            Connection: keep-alive
#            Upgrade: null
      embedding:
        base-url: http://192.168.2.54:9015
        options:
          model: multimodal-embedding
        embeddings-path: /v1/embeddings
        api-key: sk-dbc8ed51cec741d388e0ca023d33b551
