CREATE TABLE `event_detail`
(
    `event_id`                bigint NOT NULL,
    `event_type`              varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报警类型',
    `event_type_chinese`      varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '报警类型中文',
    `camera_id`               bigint                                                        DEFAULT NULL COMMENT '摄像机id',
    `edge_code`               varchar(64) COLLATE utf8mb4_general_ci                        DEFAULT NULL COMMENT '边缘设备code',
    `work_mode`               tinyint                                                       DEFAULT NULL COMMENT '边缘设备工作模式 0表示闭环运行，1表示算力资源',
    `voice`                   varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '大屏语音',
    `channel_code`            varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '通道编码',
    `camera_name`             varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '摄像机名称',
    `alarm_picture`           longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '报警图片 list json',
    `alarm_video`             longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '报警视频',
    `event_number`            varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '算法产生的事件ID',
    `alarm_count`             int                                                           DEFAULT NULL COMMENT '报警次数',
    `alarm_time`              datetime                                                      DEFAULT NULL COMMENT '告警时间',
    `alarm_latitude` double DEFAULT NULL COMMENT '火情经度',
    `alarm_longitude` double DEFAULT NULL COMMENT '火情纬度',
    `x_coordinate` double DEFAULT NULL COMMENT '告警x坐标',
    `y_coordinate` double DEFAULT NULL COMMENT '告警x坐标',
    `z_coordinate` double DEFAULT NULL COMMENT '告警x坐标',
    `camera_latitude` double DEFAULT NULL COMMENT '设备经度',
    `camera_longitude` double DEFAULT NULL COMMENT '设备纬度',
    `camera_site_name`        varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备区域简称',
    `camera_site_id`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备区域ID',
    `event_site_name`         varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发生区域全称',
    `event_site_id`           bigint                                                        DEFAULT NULL COMMENT '发生区域id',
    `preset_site`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '预置点位置',
    `serious_level`           varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '严重程度',
    `second_check_picture`    longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '二次确认图片',
    `event_second_check`      tinyint                                                       DEFAULT NULL COMMENT '二次回看状态0-待执行 1-无计划 2-已执行 3-执行异常,4-未开启',
    `event_second_check_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '二次确认状态描述',
    `boxes`                   text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
    `score` double DEFAULT NULL COMMENT '报警阈值',
    `tenant_id`               bigint                                                        DEFAULT NULL COMMENT '租户Id',
    `flow_node_number`        int                                                           DEFAULT NULL COMMENT '流程引擎节点编码',
    `event_flow_result`       tinyint                                                       DEFAULT NULL COMMENT '处理结果',
    `judge_time`              datetime                                                      DEFAULT NULL COMMENT '研判时间',
    `transfer_ids`            varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '转派人员，逗号分割',
    `dealed`                  int                                                           DEFAULT NULL COMMENT '是否及时处理（0-未处理，1-未及时处理，2-已及时处理）',
    `create_time`             datetime                                                      DEFAULT NULL,
    `creator_id`              bigint                                                        DEFAULT NULL,
    `second_big_picture`      text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '二次放大图',
    `second_big_boxes`        text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '二次放大图确认框',
    `temp_ban_ids`            text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '当前临时禁止查看人员',
    `second_check_boxes`      text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '二次回看红框',
    `event_second_check_time` datetime                                                      DEFAULT NULL COMMENT '二次确认时间',
    `camera_ptz`              json                                                          DEFAULT NULL COMMENT '相机ptz信息',
    `update_time`             datetime                                                      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `second_check_delay_min`  int                                                           DEFAULT NULL COMMENT '二次确认延后时间,单位min',
    `threshold`               float                                                         DEFAULT NULL COMMENT '算法检查阈值',
    `data_source`             int                                                           DEFAULT NULL COMMENT '数据来源 0-本平台 1-安徽项目',
    `event_org_code`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '事件组织编码',
    `flow_diagram_id`         bigint                                                        DEFAULT NULL COMMENT '流程图id',
    `flow_instance_id`        bigint                                                        DEFAULT NULL COMMENT '流程引擎流程实例id',
    `flow_node_key`           varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '流程引擎节点key',
    `flow_node_name`          varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '流程引擎节点名称',
    `preset_site_id`          bigint                                                        DEFAULT NULL COMMENT '预置点id',
    `sound_light_alarm_code`  varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '触发声光报警器码,空就不触发',
    `structured_data`         json                                                          DEFAULT NULL COMMENT '结构化数据',
    `identify_result`         varchar(500) COLLATE utf8mb4_general_ci                       DEFAULT NULL,
    `identify_detail`         json                                                          DEFAULT NULL COMMENT '识别详情',
    `false_alarm_flag`        tinyint(1) DEFAULT '0' COMMENT '是否被标记为误报 0-否 1-是',
    `flow_execute_flag`       tinyint(1) DEFAULT '0' COMMENT '是否正在执行,正在执行中的在事件审核页面屏蔽查询 0-否 1-是',
    `flow_execute_timestamp`  bigint                                                        DEFAULT NULL COMMENT '开始执行的时间戳',
    PRIMARY KEY (`event_id`) USING BTREE,
    UNIQUE KEY `flow_instance_id` (`flow_instance_id`),
    KEY                       `idx_alarm_time` (`alarm_time`) USING BTREE,
    KEY                       `idx_event_number` (`event_number`) USING BTREE,
    KEY                       `create_time` (`create_time`),
    KEY                       `update_time` (`update_time`),
    KEY                       `idx_event_second_check_time` (`event_second_check_time`) USING BTREE,
    KEY                       `idx_camera_id_event_type` (`camera_id`,`event_type`) USING BTREE,
    KEY                       `idx_event_org_code` (`event_org_code`) USING BTREE,
    KEY                       `idx_flow_execute_flag` (`flow_execute_flag`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;