-- icode_nbxc.t_hw_equipment definition
CREATE TABLE `t_hw_equipment` (
                                  `id` bigint(20) NOT NULL COMMENT '主键',
                                  `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                  `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                  `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                  `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                  `equipment_no` varchar(50) DEFAULT NULL COMMENT '设备编号',
                                  `equipment_name` varchar(255) DEFAULT NULL COMMENT '设备别名',
                                  `department_id` bigint(20) DEFAULT NULL COMMENT '组织机构id',
                                  `department_name` varchar(50) DEFAULT NULL COMMENT '组织机构名称',
                                  `eq_classify_id` bigint(20) DEFAULT NULL COMMENT '设备类型id（外键）',
                                  `eq_classify_name` varchar(20) DEFAULT NULL COMMENT '设备类型名称',
                                  `eq_relation_type` varchar(50) DEFAULT NULL COMMENT '设备关联分类（环卫人员|环卫车辆|设施）',
                                  `eq_relation_id` bigint(20) DEFAULT NULL COMMENT '设备关联Id',
                                  `sn_number` varchar(50) DEFAULT NULL COMMENT 'sn码',
                                  `iot_card` varchar(50) DEFAULT NULL COMMENT '物联网卡号',
                                  `ip_address` varchar(20) DEFAULT NULL COMMENT 'ip地址',
                                  `eq_model` varchar(50) DEFAULT NULL COMMENT '设备型号',
                                  `bind_status` varchar(4) DEFAULT '0' COMMENT '绑定状态',
                                  `eq_status` varchar(4) DEFAULT '0' COMMENT '设备状态(0:离线,1:行驶,2:停留,3:从未上线,默认从未上线,4:过期',
                                  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                                  `last_online_time` datetime DEFAULT NULL COMMENT '最后上线时间',
                                  `eq_manufacturer` varchar(20) DEFAULT NULL COMMENT '厂商名称',
                                  `classify_code` varchar(20) DEFAULT NULL COMMENT '分类名称编码',
                                  `real_time_url` varchar(255) DEFAULT NULL COMMENT '灯杆实时播放地址',
                                  `business_group_id` bigint(20) DEFAULT NULL COMMENT '业务组id',
                                  `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                  `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='环卫_设备表';


-- icode_nbxc.t_hw_equipment_infrastructure definition
CREATE TABLE `t_hw_equipment_infrastructure` (
                                                 `id` bigint(20) NOT NULL COMMENT '主键',
                                                 `equipment_id` bigint(20) DEFAULT NULL COMMENT '设备id',
                                                 `infrastructure_id` bigint(20) DEFAULT NULL COMMENT '设施id',
                                                 `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                                 `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                                 PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='环卫_基础设施-设备关联';


-- icode_nbxc.t_hw_equipment_operator definition
CREATE TABLE `t_hw_equipment_operator` (
                                           `id` bigint(20) NOT NULL COMMENT '主键',
                                           `equipment_id` bigint(20) DEFAULT NULL COMMENT '设备id',
                                           `operator_id` bigint(20) DEFAULT NULL COMMENT '作业人员id',
                                           `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                           `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                           PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='环卫_设备作业人员关联';


-- icode_nbxc.t_hw_equipment_vehicle definition
CREATE TABLE `t_hw_equipment_vehicle` (
                                          `id` bigint(20) NOT NULL COMMENT '主键',
                                          `equipment_id` bigint(20) DEFAULT NULL COMMENT '设备id',
                                          `vehicle_id` bigint(20) DEFAULT NULL COMMENT '车辆id',
                                          `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                          `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                          PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='环卫_车辆设备关联';


-- icode_nbxc.t_hw_illegal_event definition
CREATE TABLE `t_hw_illegal_event` (
                                      `id` bigint(20) NOT NULL COMMENT '主键',
                                      `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                                      `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
                                      `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                      `update_by` bigint(20) DEFAULT NULL COMMENT '更新人',
                                      `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                      `illegal_time` datetime DEFAULT NULL COMMENT '违规时间',
                                      `illegal_event_id` bigint(20) DEFAULT NULL COMMENT '违规事件ID',
                                      `illegal_event_name` varchar(255) DEFAULT NULL COMMENT '违规事件Name',
                                      `record_id` bigint(20) DEFAULT NULL COMMENT '考勤记录ID',
                                      `illegal_user_id` bigint(20) DEFAULT NULL COMMENT '违规人ID',
                                      `create_name` varchar(30) DEFAULT NULL COMMENT '创建人名称',
                                      `update_name` varchar(30) DEFAULT NULL COMMENT '更改人名称',
                                      `feedback` varchar(700) DEFAULT NULL COMMENT '异常反馈',
                                      `status` tinyint(4) DEFAULT NULL COMMENT '0.未处理,1.已处理',
                                      `duty_duration` int(11) DEFAULT '0' COMMENT '脱岗时长(分钟)/滞留时常',
                                      `post_classify` bigint(20) DEFAULT NULL COMMENT '岗位类型id',
                                      `post_name` varchar(20) DEFAULT NULL COMMENT '岗位名称',
                                      `company_id` bigint(20) DEFAULT NULL COMMENT '所属单位id',
                                      `company_name` varchar(20) DEFAULT NULL COMMENT '所属单位名称',
                                      `business_group_id` bigint(20) DEFAULT NULL COMMENT '业务组id',
                                      `business_group_name` varchar(20) DEFAULT NULL COMMENT '业务组名称',
                                      `curing_obj_id` bigint(20) DEFAULT NULL COMMENT '管养对象id',
                                      `illegal_user_name` varchar(20) DEFAULT NULL COMMENT '违规人员名称',
                                      `lat` double(20,6) DEFAULT NULL COMMENT '纬度，违规事件触发的最后点位',
                                      `lon` double(20,6) DEFAULT NULL COMMENT '经度，违规事件触发的最后点位',
                                      `violation_illegal_id` bigint(20) DEFAULT NULL COMMENT '违规事件外键ID(滞留计算)',
                                      `element_detail` varchar(255) DEFAULT NULL COMMENT '点位信息',
                                      `rule_classify` tinyint(4) DEFAULT NULL COMMENT '规则类型(0.脱岗、1.滞留、2.迟到、3.早退、4.缺勤)',
                                      `start_lat` double(20,6) DEFAULT NULL COMMENT '纬度-开始',
                                      `start_lon` double(20,6) DEFAULT NULL COMMENT '经度-开始',
                                      `end_lat` double(20,6) DEFAULT NULL COMMENT '纬度-结束',
                                      `end_lon` double(20,6) DEFAULT NULL COMMENT '经度-结束',
                                      `start_time` datetime DEFAULT NULL COMMENT '开始时间',
                                      `end_time` datetime DEFAULT NULL COMMENT '结束时间',
                                      `illegal_end` tinyint(4) DEFAULT NULL COMMENT '1：违规已结束  0：违规进行中',
                                      `processor_id` bigint(20) DEFAULT NULL COMMENT '处理人id',
                                      `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                      `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                      PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_人员事件记录';


-- icode_nbxc.t_hw_infrastructure definition
CREATE TABLE `t_hw_infrastructure` (
                                       `id` bigint(20) NOT NULL COMMENT '主键',
                                       `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                       `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                       `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                       `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                       `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                       `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                       `infrastructure_no` varchar(50) DEFAULT NULL COMMENT '设施编号',
                                       `infrastructure_name` varchar(50) DEFAULT NULL COMMENT '设施名称',
                                       `classify_id` bigint(20) DEFAULT NULL COMMENT '设施分类ID外键',
                                       `classify_name` varchar(50) DEFAULT NULL COMMENT '设施分类名称',
                                       `infrastructure_patch` text COMMENT '设施图斑',
                                       `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
                                       `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
                                       `department_id` bigint(20) DEFAULT NULL COMMENT '组织结构id',
                                       `department_name` varchar(20) DEFAULT NULL COMMENT '组织结构名称',
                                       `speed_limit` int(11) DEFAULT NULL COMMENT '限速（当类型为市政道路时录入km/h）',
                                       `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                                       `urgent_people_id` bigint(20) DEFAULT NULL COMMENT '紧急联系人id',
                                       `charge_people_id` bigint(20) DEFAULT NULL COMMENT '负责人id',
                                       `urgent_people_name` varchar(20) DEFAULT NULL COMMENT '紧急联系人名称',
                                       `charge_people_name` varchar(20) DEFAULT NULL COMMENT '负责人名称',
                                       `infrastructure_model` varchar(50) DEFAULT NULL COMMENT '设施型号',
                                       `status` varchar(4) DEFAULT '0' COMMENT '状态(1:未激活2:在线3:离线4:停用)',
                                       `element_detail` varchar(255) DEFAULT NULL COMMENT '图元详情',
                                       `region` varchar(4) DEFAULT NULL COMMENT '区域(0.南区,1.北区)',
                                       `addr` varchar(255) DEFAULT NULL COMMENT '设施地址',
                                       `is_alarm` varchar(4) DEFAULT NULL COMMENT '是否报警(1报警 0 不报警)',
                                       `last_upload_at` datetime DEFAULT NULL COMMENT '最后上报时间',
                                       `business_group_id` bigint(20) DEFAULT NULL COMMENT '业务组id',
                                       `classify_code` varchar(20) DEFAULT NULL COMMENT '分类名称编码',
                                       `real_time_url` varchar(255) DEFAULT NULL COMMENT '灯杆实时播放地址',
                                       `play_back_url` varchar(255) DEFAULT NULL COMMENT '灯杆回放地址',
                                       `install_time` datetime DEFAULT NULL COMMENT '安装时间',
                                       `curing_obj_id` bigint(20) DEFAULT NULL COMMENT '管养对象ID',
                                       `curing_classify_id` bigint(20) DEFAULT NULL COMMENT '管养对象类型ID',
                                       `contact_information` varchar(50) DEFAULT NULL COMMENT '联系方式',
                                       `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                       `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                       PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='环卫_基础设施表';


-- icode_nbxc.t_hw_motorcade definition
CREATE TABLE `t_hw_motorcade` (
                                  `id` bigint(20) NOT NULL COMMENT '主键',
                                  `motorcade_name` varchar(32) DEFAULT NULL COMMENT '车队队名',
                                  `dept_id` bigint(20) DEFAULT NULL COMMENT '责任部门主键',
                                  `user_id` bigint(20) DEFAULT NULL COMMENT '负责人主键',
                                  `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                  `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                  `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                  `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                  `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                  `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车队';


-- icode_nbxc.t_hw_motorcade_vehicle definition
CREATE TABLE `t_hw_motorcade_vehicle` (
                                          `id` bigint(20) NOT NULL COMMENT '主键',
                                          `motorcade_id` bigint(20) DEFAULT NULL COMMENT '车队id',
                                          `vehicle_id` bigint(20) DEFAULT NULL COMMENT '车辆id',
                                          `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                          `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                          PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车队车辆关联';


-- icode_nbxc.t_hw_operator definition
CREATE TABLE `t_hw_operator` (
                                 `id` bigint(20) NOT NULL COMMENT '主键',
                                 `user_name` varchar(32) DEFAULT NULL COMMENT '用户姓名',
                                 `sex` tinyint(4) DEFAULT NULL COMMENT '性别（0 男 1女）',
                                 `id_number` varchar(18) DEFAULT NULL COMMENT '身份证',
                                 `age` int(11) DEFAULT NULL COMMENT '年龄',
                                 `working_type` tinyint(4) DEFAULT NULL COMMENT '用工类型 （0 司机 1 洒水）',
                                 `drive_image_url` varchar(255) DEFAULT NULL COMMENT '驾驶证照片',
                                 `residence` varchar(255) DEFAULT NULL COMMENT '居住地',
                                 `phone` varchar(11) DEFAULT NULL COMMENT '手机号',
                                 `emergency_contact` varchar(20) DEFAULT NULL COMMENT '紧急联系人',
                                 `emergency_phone` varchar(11) DEFAULT NULL COMMENT '紧急联系人电话',
                                 `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                                 `department_id` bigint(20) DEFAULT NULL COMMENT '组织机构id',
                                 `department_name` varchar(50) DEFAULT NULL COMMENT '组织机构名称',
                                 `equipment_status` tinyint(4) DEFAULT NULL COMMENT '是否绑定设备(0.已绑定,1.未绑定)',
                                 `classify_name` varchar(20) DEFAULT NULL COMMENT '岗位名称',
                                 `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                 `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                 `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                 `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                 `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                 `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                 `contract_no` varchar(32) DEFAULT NULL COMMENT '合同编号',
                                 `contract_status` tinyint(4) DEFAULT NULL COMMENT '合同状态',
                                 `contract_type` varchar(20) DEFAULT NULL COMMENT '合同类型',
                                 `on_trial_deadline` date DEFAULT NULL COMMENT '试用期截止日',
                                 `probation_period` tinyint(4) DEFAULT NULL COMMENT '试用期(月)',
                                 `contract_term` int(11) DEFAULT NULL COMMENT '合同年限',
                                 `contract_start_time` date DEFAULT NULL COMMENT '合同开始日期',
                                 `contract_end_time` date DEFAULT NULL COMMENT '合同截止日期',
                                 `bank_of_deposit` varchar(20) DEFAULT NULL COMMENT '开户行',
                                 `bank_card_no` varchar(32) DEFAULT NULL COMMENT '银行卡号',
                                 `nation` tinyint(4) DEFAULT NULL COMMENT '民族',
                                 `political_outlook` tinyint(4) DEFAULT NULL COMMENT '政治面貌',
                                 `post_description` varchar(100) DEFAULT NULL COMMENT '岗位描述',
                                 `clothing_size` varchar(10) DEFAULT NULL COMMENT '服装尺码',
                                 `entry_date` date DEFAULT NULL COMMENT '入职日期',
                                 `insurance_type` tinyint(4) DEFAULT NULL COMMENT '保险类型',
                                 `driver_license_level` tinyint(4) DEFAULT NULL COMMENT '驾照级别',
                                 `driver_license_num` varchar(32) DEFAULT NULL COMMENT '驾驶证号',
                                 `driver_license_due_date` date DEFAULT NULL COMMENT '驾驶证到期日',
                                 `post_classify` bigint(20) DEFAULT NULL COMMENT '岗位分类ID',
                                 `post_classify_code` varchar(20) DEFAULT NULL COMMENT '岗位编码',
                                 `idcard_image_url` varchar(255) DEFAULT NULL COMMENT '身份证照片',
                                 `face_image_url` varchar(255) DEFAULT NULL COMMENT '人脸照片',
                                 `contract_subject` varchar(20) DEFAULT NULL COMMENT '合同主体',
                                 `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                 `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                 PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_环卫人员信息';


-- icode_nbxc.t_hw_people_work_record definition
CREATE TABLE `t_hw_people_work_record` (
                                           `id` bigint(20) NOT NULL COMMENT '主键',
                                           `user_id` bigint(20) DEFAULT '0' COMMENT '作业人员id',
                                           `user_name` varchar(20) DEFAULT '' COMMENT '作业人员',
                                           `user_post` bigint(20) DEFAULT NULL COMMENT '岗位id',
                                           `post_name` varchar(20) DEFAULT '' COMMENT '岗位',
                                           `work_date` date DEFAULT NULL COMMENT '作业日期',
                                           `plan_mileage` double(8,2) DEFAULT '0.00' COMMENT '计划作业里程（km）',
                                           `mileage` double(8,2) DEFAULT '0.00' COMMENT '作业里程（km）',
                                           `completion_rate` double(8,4) DEFAULT '0.0000' COMMENT '作业完成率(%)',
                                           `activity_mileage` double(8,2) DEFAULT '0.00' COMMENT '活动里程（km）',
                                           `total_mileage` double(8,2) DEFAULT '0.00' COMMENT '当日总里程（km）',
                                           `actual_working_hours` int(11) DEFAULT '0' COMMENT '实际上班时长（分钟）',
                                           `retention_time` int(11) DEFAULT '0' COMMENT '滞留时长（分钟）',
                                           `leave_time` int(11) DEFAULT '0' COMMENT '脱岗时长（分钟）',
                                           `business_group_name` varchar(50) DEFAULT '' COMMENT '业务组名称',
                                           `dept_id` bigint(20) DEFAULT NULL COMMENT '单位id',
                                           `dept_name` varchar(50) DEFAULT '' COMMENT '单位名称',
                                           `create_name` varchar(20) DEFAULT '' COMMENT '创建人',
                                           `create_by` bigint(20) DEFAULT '0' COMMENT '创建者ID',
                                           `create_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
                                           `update_name` varchar(20) DEFAULT '' COMMENT '修改人',
                                           `update_by` bigint(20) DEFAULT '0' COMMENT '修改人ID',
                                           `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                           `business_group_id` bigint(20) DEFAULT NULL COMMENT '业务组id',
                                           `trans_day` char(2) DEFAULT '0' COMMENT '排班是否跨天(0否 1是)',
                                           `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                           `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                           PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_人员作业记录表';


-- icode_nbxc.t_hw_quality_group definition
CREATE TABLE `t_hw_quality_group` (
                                      `id` bigint(20) NOT NULL COMMENT '群组ID',
                                      `father_id` bigint(20) DEFAULT '-1' COMMENT '父级群组ID',
                                      `group_name` varchar(30) NOT NULL COMMENT '群组名',
                                      `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                      `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                      `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                      `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                      `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                      `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                      `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                      `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                      PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='品质群组表';


-- icode_nbxc.t_hw_quality_group_photo_record definition
CREATE TABLE `t_hw_quality_group_photo_record` (
                                                   `id` bigint(20) NOT NULL COMMENT '拍照记录ID',
                                                   `user_id` bigint(20) DEFAULT NULL COMMENT '用户ID',
                                                   `create_time` datetime DEFAULT NULL COMMENT '创建时间（首次拍照）',
                                                   `location` varchar(100) DEFAULT NULL COMMENT '地址（首次拍照）',
                                                   `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                                   `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                                   PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='品质群组拍照记录表';


-- icode_nbxc.t_hw_quality_group_user definition
CREATE TABLE `t_hw_quality_group_user` (
                                           `user_id` bigint(20) NOT NULL COMMENT '用户ID',
                                           `group_id` bigint(20) NOT NULL COMMENT '群组ID',
                                           `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                           `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                           PRIMARY KEY (`user_id`,`group_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户和品质群组关联表';


-- icode_nbxc.t_hw_schedule_people_record definition
CREATE TABLE `t_hw_schedule_people_record` (
                                               `id` bigint(20) NOT NULL COMMENT '主键',
                                               `user_id` bigint(20) DEFAULT NULL COMMENT '作业人员id',
                                               `user_name` varchar(50) DEFAULT NULL COMMENT '作业人员',
                                               `user_post` bigint(20) DEFAULT NULL COMMENT '岗位',
                                               `dept_id` bigint(20) DEFAULT NULL COMMENT '单位id',
                                               `dept_name` varchar(50) DEFAULT NULL COMMENT '单位名称',
                                               `work_id` bigint(20) DEFAULT NULL COMMENT '班次id',
                                               `work_frequency` varchar(500) DEFAULT NULL COMMENT '班次时间',
                                               `work_name` varchar(50) DEFAULT NULL COMMENT '班次名称',
                                               `curing_id` bigint(20) DEFAULT NULL COMMENT '管养对象id',
                                               `curing_name` varchar(50) DEFAULT NULL COMMENT '管养对象名称',
                                               `segment_id` bigint(20) DEFAULT NULL COMMENT '区段id',
                                               `segment_name` varchar(50) DEFAULT NULL COMMENT '区段名称',
                                               `remark` varchar(200) DEFAULT NULL COMMENT '备注',
                                               `schedule_date` varchar(100) DEFAULT NULL COMMENT '排班日期',
                                               `rule_one` varchar(50) DEFAULT NULL COMMENT '作业规则1(json对象字符串)',
                                               `rule_two` varchar(50) DEFAULT NULL COMMENT '作业规则2',
                                               `business_group_id` bigint(20) DEFAULT NULL COMMENT '业务组id',
                                               `business_group_name` varchar(50) DEFAULT NULL COMMENT '业务组名称',
                                               `principal_name` varchar(50) DEFAULT NULL COMMENT '负责人名称（排班）',
                                               `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                               `work_date` date DEFAULT NULL COMMENT '工作时间',
                                               `work_result` varchar(50) DEFAULT NULL COMMENT '作业结果（0已完成 1未完成）',
                                               `element_detail` text COMMENT '区段详情',
                                               `post_name` varchar(20) DEFAULT NULL COMMENT '岗位名称',
                                               `attendance_record_id` bigint(20) DEFAULT NULL COMMENT '考勤记录ID',
                                               `element` text COMMENT '电子围栏',
                                               `trans_day` char(2) DEFAULT '0' COMMENT '排班是否跨天(0否 1是)',
                                               `equipment_id` bigint(20) DEFAULT NULL COMMENT '设备id',
                                               `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                               `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                               PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_人员排班记录';


-- icode_nbxc.t_hw_schedule_vehicle_record definition
CREATE TABLE `t_hw_schedule_vehicle_record` (
                                                `id` bigint(20) NOT NULL COMMENT '主键',
                                                `schedule_vehicle` bigint(20) DEFAULT NULL COMMENT '车辆排班ID',
                                                `vehicle_id` bigint(20) DEFAULT NULL COMMENT '作业车辆ID',
                                                `vehicle_name` varchar(50) DEFAULT NULL COMMENT '作业车辆名称',
                                                `vehicle_type` varchar(50) DEFAULT NULL COMMENT '车辆类型',
                                                `classify_id` bigint(20) DEFAULT NULL COMMENT '车辆环卫分类id',
                                                `work_type` varchar(50) DEFAULT NULL COMMENT '作业类型',
                                                `work_road_name` varchar(50) DEFAULT NULL COMMENT '工作路线名称',
                                                `work_road_id` bigint(20) DEFAULT NULL COMMENT '工作路线ID',
                                                `work_date` date DEFAULT NULL COMMENT '工作日期',
                                                `work_name` varchar(300) DEFAULT NULL COMMENT '班次名称',
                                                `work_id` varchar(90) DEFAULT NULL COMMENT '班次ID',
                                                `dept_name` varchar(50) DEFAULT NULL COMMENT '单位名称',
                                                `dept_id` bigint(20) DEFAULT NULL COMMENT '单位id',
                                                `curing_name` varchar(50) DEFAULT NULL COMMENT '管养对象名称',
                                                `segment_name` varchar(50) DEFAULT NULL COMMENT '区段名称',
                                                `driver_id` bigint(20) DEFAULT NULL COMMENT '司机ID',
                                                `driver_name` varchar(50) DEFAULT NULL COMMENT '司机名称',
                                                `remark` varchar(200) DEFAULT NULL COMMENT '备注',
                                                `motorcade_id` bigint(20) DEFAULT NULL COMMENT '车队id',
                                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                                `create_by` bigint(20) DEFAULT NULL COMMENT '创建人',
                                                `update_by` bigint(20) DEFAULT NULL COMMENT '更改人',
                                                `update_time` datetime DEFAULT NULL COMMENT '更改人',
                                                `create_name` varchar(50) DEFAULT NULL COMMENT '创建人名称',
                                                `update_name` varchar(50) DEFAULT NULL COMMENT '修改人名称',
                                                `work_result` varchar(50) DEFAULT NULL COMMENT '作业结果（0已完成 1未完成）',
                                                `license_number` varchar(32) DEFAULT NULL COMMENT '项目车号',
                                                `element_detail` text COMMENT '区段详情',
                                                `distance` double(8,2) DEFAULT NULL COMMENT '行驶里程',
                                                `total_dis` double(8,2) DEFAULT NULL COMMENT '总里程',
                                                `element` text COMMENT '电子围栏',
                                                `person_liable` varchar(50) DEFAULT NULL COMMENT '责任人',
                                                `vehicle_type_name` varchar(50) DEFAULT NULL COMMENT '车辆类型名称',
                                                `work_frequency` text COMMENT '班次时间',
                                                `motorcade_name` varchar(50) DEFAULT NULL COMMENT '车队名称',
                                                `export_usr` varchar(30) DEFAULT NULL COMMENT '导入人',
                                                `plan_work_duration` int(11) DEFAULT NULL COMMENT '计划作业时长',
                                                `plate_number` varchar(20) DEFAULT NULL COMMENT '车牌号',
                                                `task_config_id` bigint(20) DEFAULT NULL COMMENT '作业配置id',
                                                `trans_day` char(2) DEFAULT '0' COMMENT '排班是否跨天(0否 1是)',
                                                `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                                `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车辆排班记录';


-- icode_nbxc.t_hw_segment definition
CREATE TABLE `t_hw_segment` (
                                `id` bigint(20) NOT NULL COMMENT '主键',
                                `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                `segment_code` varchar(50) DEFAULT NULL COMMENT '区段编号',
                                `segment_name` varchar(50) DEFAULT NULL COMMENT '区段名称',
                                `type_code` varchar(50) DEFAULT NULL COMMENT '区段类型编码',
                                `type_shape` varchar(50) DEFAULT NULL COMMENT '区段外形（1点2多折线3多边形4矩形5圆形）',
                                `department_id` bigint(20) DEFAULT NULL COMMENT '所属部门id',
                                `department_name` varchar(50) DEFAULT NULL COMMENT '所属部门名称',
                                `element_area` decimal(10,2) DEFAULT NULL COMMENT '图元面积（m2）',
                                `actual_area` decimal(10,2) DEFAULT NULL COMMENT '实际面积（m2）',
                                `segment_describe` varchar(255) DEFAULT NULL COMMENT '区段描述',
                                `element_detail` text COMMENT '图元详细',
                                `segment_type` tinyint(4) DEFAULT NULL COMMENT '区段所属类型（1人员 2车辆）',
                                `element` text COMMENT '图元',
                                `dept_id` bigint(20) DEFAULT NULL COMMENT '单位ID',
                                `dept_name` varchar(50) DEFAULT NULL COMMENT '单位名称',
                                `route_length` double(8,2) DEFAULT NULL COMMENT '路线长度',
                                `group_id` bigint(20) DEFAULT NULL COMMENT '业务组id或者车队id',
                                `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_扫保区段管理';


-- icode_nbxc.t_hw_shape_point definition
CREATE TABLE `t_hw_shape_point` (
                                    `id` bigint(20) NOT NULL COMMENT '主键',
                                    `shape_id` bigint(20) NOT NULL COMMENT '关联hw_curing_obj表的主键id',
                                    `the_geom` mediumtext COMMENT '点位信息',
                                    `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                    `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_管养设施点位';

-- icode_nbxc.t_hw_sys_annex definition
CREATE TABLE `t_hw_sys_annex` (
                                  `id` bigint(20) NOT NULL COMMENT '主键',
                                  `create_by` bigint(20) DEFAULT NULL COMMENT '创建人id',
                                  `create_name` varchar(20) DEFAULT NULL COMMENT '创建人姓名',
                                  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                  `create_department_id` varchar(50) DEFAULT NULL COMMENT '创建人所在部门',
                                  `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                  `update_by` bigint(20) DEFAULT NULL COMMENT '修改人',
                                  `update_name` varchar(20) DEFAULT NULL COMMENT '修改人姓名',
                                  `update_department_id` varchar(50) DEFAULT NULL COMMENT '修改人所在部门',
                                  `delete_mark` int(11) DEFAULT NULL COMMENT '是否删除',
                                  `enabled_mark` int(11) DEFAULT NULL COMMENT '是否启用',
                                  `sort_code` bigint(20) DEFAULT NULL COMMENT '排序',
                                  `file_name` varchar(100) DEFAULT NULL COMMENT '文件名',
                                  `file_size` bigint(20) DEFAULT NULL COMMENT '文件大小',
                                  `file_type` varchar(50) DEFAULT NULL COMMENT '文件类型',
                                  `group_id` varchar(50) DEFAULT NULL COMMENT '文件分组',
                                  `file_path` varchar(1000) DEFAULT NULL COMMENT '路径',
                                  `save_mode` varchar(50) DEFAULT NULL COMMENT '存储方式 local 本地存储     aliyun 阿里云OSS存储',
                                  `download_count` bigint(20) DEFAULT NULL COMMENT '下载量',
                                  `lat` double(20,8) DEFAULT NULL COMMENT '纬度',
                                  `lon` double(20,8) DEFAULT NULL COMMENT '经度',
                                  `location` varchar(255) DEFAULT NULL COMMENT '拍照地址',
                                  `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                  `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                  PRIMARY KEY (`id`) USING BTREE,
                                  KEY `idx_annex_group_sort` (`group_id`,`sort_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Annex';


-- icode_nbxc.t_hw_sys_dept definition
CREATE TABLE `t_hw_sys_dept` (
                                 `dept_id` bigint(20) NOT NULL COMMENT '部门id',
                                 `parent_id` bigint(20) DEFAULT '0' COMMENT '父部门id',
                                 `ancestors` text COMMENT '祖级列表',
                                 `dept_name` varchar(30) DEFAULT '' COMMENT '部门名称',
                                 `order_num` int(11) DEFAULT '0' COMMENT '显示顺序',
                                 `leader` varchar(20) DEFAULT NULL COMMENT '负责人',
                                 `phone` varchar(11) DEFAULT NULL COMMENT '联系电话',
                                 `email` varchar(50) DEFAULT NULL COMMENT '邮箱',
                                 `status` char(1) DEFAULT '0' COMMENT '部门状态（0正常 1停用）',
                                 `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
                                 `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
                                 `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                 `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
                                 `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                 `create_department` varchar(255) DEFAULT NULL COMMENT '创建者部门',
                                 `update_department` varchar(255) DEFAULT NULL COMMENT '更新者部门',
                                 `tenantId` varchar(255) DEFAULT NULL,
                                 `UniId` varchar(255) DEFAULT NULL,
                                 `ParentDepartmentId` varchar(255) DEFAULT NULL COMMENT '上级部门',
                                 `short_name` varchar(255) DEFAULT NULL COMMENT '部门简称',
                                 `main_post` bigint(20) DEFAULT '-1' COMMENT '部门主职主键',
                                 `main_post_name` varchar(255) DEFAULT NULL COMMENT '部门主职名称',
                                 `charge_main_post` varchar(255) DEFAULT NULL COMMENT '分管主键',
                                 `charge_main_post_name` varchar(255) DEFAULT NULL COMMENT '分管名称',
                                 `description` varchar(255) DEFAULT NULL COMMENT '描述',
                                 `department_level` int(11) DEFAULT NULL COMMENT '部门层次',
                                 `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                                 `partner` varchar(255) DEFAULT NULL COMMENT '是否合作单位(0.是,1.否)',
                                 `dept_code` varchar(20) DEFAULT NULL COMMENT '部门编码',
                                 `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                 `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                 PRIMARY KEY (`dept_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='环卫_部门表';


-- icode_nbxc.t_hw_sys_user definition
CREATE TABLE `t_hw_sys_user` (
                                 `user_id` bigint(20) NOT NULL COMMENT '用户ID',
                                 `dept_id` bigint(20) DEFAULT NULL COMMENT '部门ID',
                                 `main_post_id` bigint(20) DEFAULT NULL COMMENT '主岗ID',
                                 `user_name` varchar(30) NOT NULL COMMENT '用户账号',
                                 `nick_name` varchar(30) NOT NULL COMMENT '用户昵称',
                                 `user_type` varchar(2) DEFAULT '00' COMMENT '用户类型（00系统用户）',
                                 `email` varchar(50) DEFAULT NULL COMMENT '用户邮箱',
                                 `phonenumber` varchar(11) DEFAULT NULL COMMENT '手机号码',
                                 `sex` char(1) DEFAULT '0' COMMENT '用户性别（0男 1女 2未知）',
                                 `avatar` varchar(100) DEFAULT NULL COMMENT '头像地址',
                                 `password` varchar(100) DEFAULT NULL COMMENT '密码',
                                 `status` char(1) DEFAULT '0' COMMENT '帐号状态（0正常 1停用）',
                                 `del_flag` char(1) DEFAULT '0' COMMENT '删除标志（0代表存在 2代表删除）',
                                 `login_ip` varchar(128) DEFAULT NULL COMMENT '最后登录IP',
                                 `login_date` datetime DEFAULT NULL COMMENT '最后登录时间',
                                 `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
                                 `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                 `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
                                 `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                 `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                 `user_info_id` varchar(32) DEFAULT NULL COMMENT '所接收的管理人员id',
                                 `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                 `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                 PRIMARY KEY (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息表';


-- icode_nbxc.t_hw_vehicle definition
CREATE TABLE `t_hw_vehicle` (
                                `id` bigint(20) NOT NULL COMMENT '主键',
                                `classify_id` bigint(20) DEFAULT NULL COMMENT '车辆环卫分类id',
                                `vehicle_name` varchar(20) DEFAULT NULL COMMENT '车辆名称',
                                `vehicle_number` varchar(32) DEFAULT NULL COMMENT '车辆编号',
                                `plate_number` varchar(32) DEFAULT NULL COMMENT '车牌号',
                                `vehicle_type` bigint(20) DEFAULT NULL COMMENT '车辆类型',
                                `vehicle_kinds` tinyint(4) DEFAULT NULL COMMENT '车辆种类',
                                `vehicle_brand` varchar(20) DEFAULT NULL COMMENT '车辆品牌',
                                `vehicle_model` varchar(20) DEFAULT NULL COMMENT '车辆型号',
                                `vehicle_ident_number` varchar(32) DEFAULT NULL COMMENT '车辆识别代码',
                                `engine_number` varchar(32) DEFAULT NULL COMMENT '发动机号',
                                `vehicle_use` tinyint(4) DEFAULT NULL COMMENT '车辆用途',
                                `vehicle_nature` tinyint(4) DEFAULT NULL COMMENT '车辆性质',
                                `vehicle_properties` tinyint(4) DEFAULT NULL COMMENT '车辆属性',
                                `vehicle_status` tinyint(4) DEFAULT NULL COMMENT '车辆状态(离线|在线|停车|报警|未定位)',
                                `speed` double(10,2) DEFAULT NULL COMMENT '作业速度(km/h)',
                                `usage_status` tinyint(4) DEFAULT NULL COMMENT '使用状态',
                                `power_type` tinyint(4) DEFAULT NULL COMMENT '动力类型',
                                `vehicle_tonnage` varchar(20) DEFAULT NULL COMMENT '车辆吨位',
                                `license_plate_color` tinyint(4) DEFAULT NULL COMMENT '牌照颜色',
                                `production_date` date DEFAULT NULL COMMENT '出厂日期',
                                `registration_date` date DEFAULT NULL COMMENT '注册登记日期',
                                `service_life` varchar(20) DEFAULT NULL COMMENT '使用年限',
                                `approved_capacity` double(10,2) DEFAULT NULL COMMENT '核定载质量(kg)',
                                `curb_weight` double(10,2) DEFAULT NULL COMMENT '整备质量(kg)',
                                `own_quality` double(10,2) DEFAULT NULL COMMENT '自有质量(kg)',
                                `district` varchar(32) DEFAULT NULL COMMENT '行政区划',
                                `vehicle_photo` varchar(100) DEFAULT NULL COMMENT '车辆照片',
                                `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                                `use_company` varchar(32) DEFAULT NULL COMMENT '使用单位',
                                `use_department` bigint(20) DEFAULT NULL COMMENT '使用部门id',
                                `use_department_name` varchar(32) DEFAULT NULL COMMENT '使用部门名称',
                                `department` bigint(20) DEFAULT NULL COMMENT '所属部门id',
                                `department_name` varchar(32) DEFAULT NULL COMMENT '所属部门名称',
                                `requirement` tinyint(4) DEFAULT NULL COMMENT '驾驶证要求',
                                `driving_license` tinyint(4) DEFAULT NULL COMMENT '有无行驶证',
                                `driving_license_photo` varchar(100) DEFAULT NULL COMMENT '行驶证照片',
                                `annual_review_date` date DEFAULT NULL COMMENT '到期年审日期',
                                `register_certificate` tinyint(4) DEFAULT NULL COMMENT '有无登记证书',
                                `register_certificate_photo` varchar(100) DEFAULT NULL COMMENT '登记证书照片',
                                `certificate_conformity` tinyint(4) DEFAULT NULL COMMENT '有无合格证',
                                `certificate_conformity_photo` varchar(100) DEFAULT NULL COMMENT '合格证照片',
                                `purchase_invoice` varchar(100) DEFAULT NULL COMMENT '购车发票',
                                `purchase_time` date DEFAULT NULL COMMENT '购车时间',
                                `purchase_amount` decimal(10,2) DEFAULT NULL COMMENT '购置金额',
                                `vehicle_price` decimal(10,2) DEFAULT NULL COMMENT '车辆原值',
                                `purchase_tax` decimal(10,2) DEFAULT NULL COMMENT '采购税金',
                                `fuel_label` tinyint(4) DEFAULT NULL COMMENT '燃料标号',
                                `emission_standard` tinyint(4) DEFAULT NULL COMMENT '排放标准',
                                `approved_manned` int(11) DEFAULT NULL COMMENT '核定载人',
                                `displacement` double(10,2) DEFAULT NULL COMMENT '排量',
                                `power` double(10,2) DEFAULT NULL COMMENT '功率',
                                `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                `distance` double(8,2) DEFAULT NULL COMMENT '行驶里程',
                                `total_dis` double(8,2) DEFAULT NULL COMMENT '总里程',
                                `oil` double(8,2) DEFAULT NULL COMMENT '油量',
                                `driver_id` bigint(20) DEFAULT NULL COMMENT '驾驶员id',
                                `driver_name` varchar(20) DEFAULT NULL COMMENT '驾驶员名称',
                                `frame_no` varchar(32) DEFAULT NULL COMMENT '车架号',
                                `factory_no` varchar(32) DEFAULT NULL COMMENT '出厂编号',
                                `oil_consumption` double(10,5) DEFAULT NULL COMMENT '定额油耗',
                                `working_vehicles` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否作业车辆  0：否  1：是',
                                `auxiliary_engine` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否有副发动机  0：否  1：是',
                                `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车辆信息';


-- icode_nbxc.t_hw_vehicle_classify definition
CREATE TABLE `t_hw_vehicle_classify` (
                                         `id` bigint(20) NOT NULL COMMENT '主键',
                                         `classify_name` varchar(20) DEFAULT NULL COMMENT '分类名称',
                                         `on_line_icon` varchar(100) DEFAULT NULL COMMENT '在线图标',
                                         `call_police_icon` varchar(100) DEFAULT NULL COMMENT '报警图标',
                                         `parking_icon` varchar(100) DEFAULT NULL COMMENT '停车图标',
                                         `not_located_icon` varchar(100) DEFAULT NULL COMMENT '未定位图标',
                                         `off_line_icon` varchar(100) DEFAULT NULL COMMENT '离线图标',
                                         `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                         `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                         `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                         `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                         `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                         `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                         `classify_code` varchar(20) DEFAULT NULL COMMENT '分类名称编码',
                                         `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                         `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                         PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车辆分类';


-- icode_nbxc.t_hw_vehicle_illegal_event definition
CREATE TABLE `t_hw_vehicle_illegal_event` (
                                              `id` bigint(20) NOT NULL COMMENT '主键',
                                              `illegal_time` datetime DEFAULT NULL COMMENT '违规时间',
                                              `illegal_event_id` bigint(20) DEFAULT NULL COMMENT '违规事件ID',
                                              `illegal_event_name` varchar(50) DEFAULT NULL COMMENT '违规事件名称',
                                              `record_id` bigint(20) DEFAULT NULL COMMENT '车辆排班记录id',
                                              `illegal_vehicle_id` bigint(20) DEFAULT NULL COMMENT '违规车辆id',
                                              `create_name` varchar(20) DEFAULT NULL COMMENT '创建人',
                                              `create_by` bigint(20) DEFAULT NULL COMMENT '创建者ID',
                                              `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                              `update_name` varchar(20) DEFAULT NULL COMMENT '修改人',
                                              `update_by` bigint(20) DEFAULT NULL COMMENT '修改人ID',
                                              `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                              `feedback` varchar(700) DEFAULT NULL COMMENT '异常反馈',
                                              `duration` int(11) DEFAULT '0' COMMENT '持续时间',
                                              `start_time` datetime DEFAULT NULL COMMENT '开始时间',
                                              `end_time` datetime DEFAULT NULL COMMENT '结束时间',
                                              `rule_classify` tinyint(4) DEFAULT NULL COMMENT '违规类型(1.空驶、2.作业偏离、3.超时停车、4.行驶超速、5.作业中超速)',
                                              `start_lat` double(20,8) DEFAULT NULL COMMENT '纬度-开始',
                                              `start_lon` double(20,8) DEFAULT NULL COMMENT '经度-开始',
                                              `end_lat` double(20,8) DEFAULT NULL COMMENT '纬度-结束',
                                              `end_lon` double(20,8) DEFAULT NULL COMMENT '经度-结束',
                                              `plate_number` varchar(32) DEFAULT NULL COMMENT '车牌号',
                                              `vehicle_name` varchar(20) DEFAULT NULL COMMENT '车辆名称(项目车号)',
                                              `driver_name` varchar(50) DEFAULT NULL COMMENT '司机名称',
                                              `motorcade_id` bigint(20) DEFAULT NULL COMMENT '车队ID',
                                              `motorcade_name` varchar(32) DEFAULT NULL COMMENT '车队名称',
                                              `dept_id` bigint(20) DEFAULT NULL COMMENT '责任部门ID',
                                              `dept_name` varchar(50) DEFAULT NULL COMMENT '责任部门名称',
                                              `user_name` varchar(50) DEFAULT NULL COMMENT '负责人名称',
                                              `license_number` varchar(32) DEFAULT NULL COMMENT '项目车号',
                                              `status` tinyint(4) DEFAULT NULL COMMENT '0.未处理,1.已处理',
                                              `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                              `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                              PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车辆事件记录';


-- icode_nbxc.t_hw_vehicle_work_record definition
CREATE TABLE `t_hw_vehicle_work_record` (
                                            `id` bigint(20) NOT NULL COMMENT '主键',
                                            `sn_number` varchar(50) DEFAULT NULL COMMENT '设备编码',
                                            `vl_id` bigint(20) DEFAULT '0' COMMENT '车辆ID',
                                            `vehicle_name` varchar(20) DEFAULT '' COMMENT '车牌号码',
                                            `plan_mileage` double(8,2) DEFAULT '0.00' COMMENT '计划作业里程(KM)',
                                            `completion_rate` double(8,4) DEFAULT '0.0000' COMMENT '作业完成率(%)',
                                            `work_date` date DEFAULT NULL COMMENT '作业日期',
                                            `distance` double(8,2) unsigned zerofill DEFAULT '00000.00' COMMENT '车辆行驶里程(km)',
                                            `work_mileage` double(8,2) DEFAULT '0.00' COMMENT '车辆作业里程(km)',
                                            `work_duration` double(8,2) DEFAULT '0.00' COMMENT '作业时长(分钟)',
                                            `driving_work_duration` double(8,2) DEFAULT '0.00' COMMENT '行驶作业时长(分钟)',
                                            `dock_work_duration` double(8,2) DEFAULT '0.00' COMMENT '停靠作业时长(分钟)',
                                            `average_travelling_speed` double(8,4) DEFAULT '0.0000' COMMENT '平均行驶速度(km/h)',
                                            `average_operating_speed` double(8,4) DEFAULT '0.0000' COMMENT '平均作业速度(km/h)',
                                            `working_duration` double(8,2) DEFAULT '0.00' COMMENT '上班时长（分钟）',
                                            `online_duration` double(8,4) DEFAULT NULL,
                                            `power_stop_duration` int(11) DEFAULT '0' COMMENT '通电停靠时长（分钟）',
                                            `max_speed` double(8,2) DEFAULT '0.00' COMMENT '最高时速（km/h）',
                                            `start_time` datetime DEFAULT NULL COMMENT '开始时间',
                                            `end_time` datetime DEFAULT NULL COMMENT '结束时间',
                                            `license_number` varchar(32) DEFAULT NULL COMMENT '项目车号',
                                            `driver_name` varchar(50) DEFAULT NULL COMMENT '当值司机',
                                            `vehicle_type_name` varchar(50) DEFAULT NULL COMMENT '车辆类型名称',
                                            `vehicle_tonnage` varchar(20) DEFAULT NULL COMMENT '车辆吨位',
                                            `dept_name` varchar(50) DEFAULT NULL COMMENT '责任部门名称',
                                            `dept_id` bigint(20) DEFAULT NULL COMMENT '责任部门ID',
                                            `duty_officer` varchar(50) DEFAULT NULL COMMENT '责任人名称',
                                            `motorcade_name` varchar(32) DEFAULT NULL COMMENT '车队名称',
                                            `motorcade_id` bigint(20) DEFAULT NULL COMMENT '车队ID',
                                            `stop_num` int(11) DEFAULT '0' COMMENT '停留次数',
                                            `stay_length` int(11) DEFAULT '0' COMMENT '停留时长',
                                            `daily_driving_duration` double(8,2) DEFAULT '0.00' COMMENT '日行驶时长',
                                            `daily_work_duration` double(8,2) DEFAULT '0.00' COMMENT '每日作业时长',
                                            `absence_duration` int(11) DEFAULT '0' COMMENT '空驶时长',
                                            `supercar_parking_duration` int(11) DEFAULT '0' COMMENT '超时停车时长',
                                            `deviate_duration` int(11) DEFAULT '0' COMMENT '偏离时长',
                                            `work_over_speed_duration` int(11) DEFAULT '0' COMMENT '作业超速时长',
                                            `driving_over_speed_duration` int(11) DEFAULT '0' COMMENT '行驶超速时长',
                                            `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                            `update_time` datetime DEFAULT NULL COMMENT '修改时间',
                                            `ins_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
                                            `upd_db_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间',
                                            PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='智慧环卫_车辆作业记录';